### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by ganiular** [UjwalBattar/eCommerce-hello-world#10]
I am learning how to deploy me first smart contarct, this this error is preventing to continue

`tronbox version`
Tronbox v2.7.14
Solidity v0.5.14 (tron-solc)

`tronbox migrate --reset --nexwork shasta`
Using network 'development'.

(node:341) UnhandledPromiseRejectionWarning: Error: Invalid URL provided to HttpProvider
    at new e (/home/ganiular/.nvm/versions/node/v14.14.0/lib/node_modules/tronbox/node_modules/tronweb/dist/webpack:/src/lib/providers/HttpProvider.js:7:19)
    at Object.create (/home/ganiular/.nvm/versions/node/v14.14.0/lib/node_modules/tronbox/build/components/Provider/index.js:1:1403)
    at Config.get [as provider] (/home/ganiular/.nvm/versions/node/v14.14.0/lib/node_modules/tronbox/build/components/Config.js:1:6101)
    at /home/ganiular/.nvm/versions/node/v14.14.0/lib/node_modules/tronbox/node_modules/@truffle/expect/index.js:4:18
    at Array.forEach (<anonymous>)
    at Object.options (/home/ganiular/.nvm/versions/node/v14.14.0/lib/node_modules/tronbox/node_modules/@truffle/expect/index.js:3:19)
    at Object.run (/home/ganiular/.nvm/versions/node/v14.14.0/lib/node_modules/tronbox/build/components/Migrate/index.js:1:3283)
    at /home/ganiular/.nvm/versions/node/v14.14.0/lib/node_modules/tronbox/build/lib/commands/migrate.js:1:1229
    at Object.needsMigrating (/home/ganiular/.nvm/versions/node/v14.14.0/lib/node_modules/tronbox/build/components/Migrate/index.js:1:6092)
    at runMigrations (/home/ganiular/.nvm/versions/node/v14.14.0/lib/node_modules/tronbox/build/lib/commands/migrate.js:1:1096)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:341) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:341) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by stevenstc** [comment]
i directly use http://www.tronide.io/ to deploy and compile the archives
