### ISSUE TITLE
Error: Invalid URL provided to HttpProvider

### ISSUE THREAD

**Issue by mahdi-ln** [UjwalBattar/eCommerce-hello-world#9]
``` 
>tronbox.cmd migrate
Using network 'development'.
Error: Invalid URL provided to HttpProvider
    at new e (C:\Users\m\AppData\Roaming\npm\node_modules\tronbox\node_modules\tronweb\dist\webpack:\src\lib\providers\HttpProvider.js:7:19)
    at Object.create (C:\Users\m\AppData\Roaming\npm\node_modules\tronbox\build\components\Provider\index.js:1:1403)
    at Config.get [as provider] (C:\Users\m\AppData\Roaming\npm\node_modules\tronbox\build\components\Config.js:1:6101)
    at provision (C:\Users\m\AppData\Roaming\npm\node_modules\tronbox\build\components\Provisioner.js:1:79)
    at Resolver.require (C:\Users\m\AppData\Roaming\npm\node_modules\tronbox\build\components\Resolver\index.js:1:817)
    at Object.lastCompletedMigration (C:\Users\m\AppData\Roaming\npm\node_modules\tronbox\build\components\Migrate\index.js:1:5491)
    at Object.needsMigrating (C:\Users\m\AppData\Roaming\npm\node_modules\tronbox\build\components\Migrate\index.js:1:6117)
    at runMigrations (C:\Users\m\AppData\Roaming\npm\node_modules\tronbox\build\lib\commands\migrate.js:1:1096)
    at C:\Users\m\AppData\Roaming\npm\node_modules\tronbox\build\lib\commands\migrate.js:1:1608
    at C:\Users\m\AppData\Roaming\npm\node_modules\tronbox\build\lib\environment.js:1:1546
Error: Invalid URL provided to HttpProvider
    at new e (C:\Users\m\AppData\Roaming\npm\node_modules\tronbox\node_modules\tronweb\dist\webpack:\src\lib\providers\HttpProvider.js:7:19)
    at Object.create (C:\Users\m\AppData\Roaming\npm\node_modules\tronbox\build\components\Provider\index.js:1:1403)
    at Config.get [as provider] (C:\Users\m\AppData\Roaming\npm\node_modules\tronbox\build\components\Config.js:1:6101)
    at provision (C:\Users\m\AppData\Roaming\npm\node_modules\tronbox\build\components\Provisioner.js:1:79)
    at Resolver.require (C:\Users\m\AppData\Roaming\npm\node_modules\tronbox\build\components\Resolver\index.js:1:817)
    at Object.lastCompletedMigration (C:\Users\m\AppData\Roaming\npm\node_modules\tronbox\build\components\Migrate\index.js:1:5491)
    at Object.needsMigrating (C:\Users\m\AppData\Roaming\npm\node_modules\tronbox\build\components\Migrate\index.js:1:6117)
    at runMigrations (C:\Users\m\AppData\Roaming\npm\node_modules\tronbox\build\lib\commands\migrate.js:1:1096)
    at C:\Users\m\AppData\Roaming\npm\node_modules\tronbox\build\lib\commands\migrate.js:1:1608
    at C:\Users\m\AppData\Roaming\npm\node_modules\tronbox\build\lib\environment.js:1:1546
```

**Comment by stevenstc** [comment]
Same error

**Comment by elbaruni** [comment]
check this 
https://github.com/ThisIsCodeXpert/Tron-TRX-DApp-Tutorial-Series/issues/1#issuecomment-727107539

**Comment by elbaruni** [comment]
> Same error

https://github.com/ThisIsCodeXpert/Tron-TRX-DApp-Tutorial-Series/issues/1#issuecomment-727107539

**Comment by stevenstc** [comment]
i directly use http://www.tronide.io/ to deploy and compile the archives
